### ISSUE TITLE
Missed go.mod file for posibillity to compile

### ISSUE THREAD

**Issue by vargrant** [lukechampine/walrus-cli#6]
I tried to add next go.mod file - after this was compiled 
-------------
module lukechampine.com/walrus-cli

go 1.13

require (
        github.com/julienschmidt/httprouter v1.3.0
        github.com/karalabe/hid v1.0.0 // indirect
        gitlab.com/NebulousLabs/Sia v1.4.1
        golang.org/x/crypto v0.0.0-20190701094942-4def268fd1a4
        lukechampine.com/flagg v1.1.1
        lukechampine.com/sialedger v0.0.0-20190804211231-0e9955f04f66
        lukechampine.com/us v0.11.1
)

replace github.com/coreos/bbolt => ../../gitlab.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt
-------------

**Comment by lukechampine** [comment]
It shouldn't be necessary to add a `replace` directive for this go.mod. `walrus` needs it because it imports the consensus database from `Sia`, but `walrus-cli` doesn't need the consensus database; it just needs to talk to `walrus`.

Anyway, I've added a `go.mod`, so everything should work now. Thanks!

(btw, use ``` to format code blocks)
